### ISSUE TITLE
Problems with Patrol Mode and Money (Lost 58k in Patrol Mode)

### ISSUE THREAD

**Issue by Yomamas232** [FiddyPercent/FiddyCraft#16]
I lost 58k while I was in patrol mode. It was most likely due to helping Boone catch a criminal with it on, but Boone was the only one who landed the hits on him. I really hope this gets fixed soon and I get my money back.

**Comment by FiddyPercent** [comment]
found the issue is fixed (will update will be put in today)
your money will be returned

**Comment by Yomamas232** [comment]
Thank you Fids! :D
